[theme]
name = 'Bibata'
description = 'Modified Generic Bibata'
version = '0.1'
author = 'ATM Jahid Hasan'

[config]
shape_size = 256
x_hotspot = 128
y_hotspot = 128
anim_delay = 40
x11_sizes = [16, 24, 32, 40, 48]

[cursors]
[cursors.bd_double_arrow]
symlinks = ['nwse-resize', 'size_fdiag']
hash_syms = ['c7088f0f3e6c8088236ef8e1e3e70000']

[cursors.bottom_left_corner]
x_hotspot = 26
y_hotspot = 232
symlinks = ['sw-resize']

[cursors.bottom_right_corner]
x_hotspot = 229
y_hotspot = 232
symlinks = ['se-resize']

[cursors.bottom_side]
x_hotspot = 129
y_hotspot = 234
symlinks = ['s-resize']

[cursors.bottom_tee]
x_hotspot = 128
y_hotspot = 230

[cursors.center_ptr]
x_hotspot = 127
y_hotspot = 17

[cursors.circle]
x_hotspot = 55
y_hotspot = 17
symlinks = ['forbidden']

[cursors.context-menu]
x_hotspot = 57
y_hotspot = 17

[cursors.copy]
x_hotspot = 55
y_hotspot = 17
hash_syms = [
  '1081e37283d90000800003c07f3ef6bf',
  '6407b0e94181790501fd1e167b474872',
  'b66166c04f8c3109214a4fbd64a50fc8'
]

[cursors.cross]
symlinks = ['cross_reverse', 'diamond_cross']

[cursors.crossed_circle]
symlinks = ['not-allowed']
hash_syms = ['03b6e0fcb3499374a867c041f52298f0']

[cursors.crosshair]

[cursors.dnd_no_drop]
x_hotspot = 100
y_hotspot = 65
symlinks = ['no-drop']

[cursors.dnd-ask]
x_hotspot = 100
y_hotspot = 65

[cursors.dnd-copy]
x_hotspot = 100
y_hotspot = 65

[cursors.dnd-link]
x_hotspot = 100
y_hotspot = 65
symlinks = ['alias']

[cursors.dotbox]
symlinks = ['dot_box_mask', 'draped_box', 'icon', 'target']

[cursors.fd_double_arrow]
symlinks = ['nesw-resize', 'size_bdiag']
hash_syms = ['fcf1c3c7cd4491d801f1e1c78f100000']

[cursors.grabbing]
x_hotspot = 128
y_hotspot = 66
symlinks = [
  'closedhand',
  'dnd-move',
  'dnd-none',
]
hash_syms = ['fcf21c00b30f7e3f83fe0dfd12e71cff']

[cursors.hand1]
x_hotspot = 144
y_hotspot = 79
symlinks = ['grab', 'openhand']

[cursors.hand2]
x_hotspot = 114
y_hotspot = 18
symlinks = [
  'pointer',
  'pointing_hand',
]
hash_syms = [
  '9d800788f1b08800ae810202380a0822',
  'e29285e634086352946a0e7090d73106'
]

[cursors.left_ptr]
x_hotspot = 55
y_hotspot = 17
symlinks = ['arrow', 'default', 'top_left_arrow']

[cursors.left_ptr_watch]
x_hotspot = 55
y_hotspot = 17
symlinks = [
  'progress'
]
hash_syms = [
  '00000000000000020006000e7e9ffc3f',
  '08e8e1c95fe2fc01f976f1e063a24ccd',
  '3ecb610c1bf2410f44200f48c40d3599',
]

[cursors.left_side]
x_hotspot = 21
y_hotspot = 128
symlinks = ['w-resize']

[cursors.left_tee]
x_hotspot = 230
y_hotspot = 128

[cursors.link]
x_hotspot = 55
y_hotspot = 17
hash_syms = [
  '3085a0e285430894940527032f8b26df',
  '640fb0e74195791501fd1ed57b41487f',
  'a2a266d0498c3104214a47bd64ab0fc8',
]

[cursors.ll_angle]
x_hotspot = 30
y_hotspot = 223

[cursors.lr_angle]
x_hotspot = 224
y_hotspot = 230

[cursors.move]
symlinks = [
  'all-scroll',
  'fleur',
  'size_all'
]
hash_syms = [
  '4498f0e0c1937ffe01fd06f973665830',
  '9081237383d90e509aa00f00170e968f'
]

[cursors.pencil]
x_hotspot = 46
y_hotspot = 211
symlinks = ['draft']

[cursors.plus]
symlinks = ['cell']

[cursors.pointer-move]
x_hotspot = 55
y_hotspot = 17

[cursors.question_arrow]
x_hotspot = 42
y_hotspot = 86
symlinks = [
  'help',
  'left_ptr_help',
  'whats_this',
]
hash_syms = [
  '5c6cd98b3f3ebcb1f9c7f1c204630408',
  'd9ce0ab605698f320427677b458ad60b',
]

[cursors.right_ptr]
x_hotspot = 204
y_hotspot = 17
symlinks = ['draft_large', 'draft_small']

[cursors.right_side]
x_hotspot = 233
y_hotspot = 128
symlinks = ['e-resize']

[cursors.right_tee]
x_hotspot = 29
y_hotspot = 128

[cursors.sb_down_arrow]
x_hotspot = 128
y_hotspot = 222
symlinks = ['down-arrow']

[cursors.sb_h_double_arrow]
symlinks = [
  'col-resize',
  'ew-resize',
  'h_double_arrow',
  'size-hor',
  'size_hor',
  'split_h',
]
hash_syms = [
  '028006030e0e7ebffc7f7070c0600140',
  '14fef782d02440884392942c1120523'
]

[cursors.sb_left_arrow]
x_hotspot = 33
y_hotspot = 128
symlinks = ['left-arrow']

[cursors.sb_right_arrow]
x_hotspot = 223
y_hotspot = 128
symlinks = ['right-arrow']

[cursors.sb_up_arrow]
x_hotspot = 128
y_hotspot = 33
symlinks = ['up-arrow']

[cursors.sb_v_double_arrow]
symlinks = [
  'double_arrow',
  'ns-resize',
  'row-resize',
  'size-ver',
  'size_ver',
  'split_v',
  'v_double_arrow',
]
hash_syms = [
  '00008160000006810000408080010102',
  '2870a09082c103050810ffdffffe0204'
]

[cursors.tcross]
symlinks = ['color-picker']

[cursors.top_left_corner]
x_hotspot = 29
y_hotspot = 24
symlinks = ['nw-resize']

[cursors.top_right_corner]
x_hotspot = 229
y_hotspot = 24
symlinks = ['ne-resize']

[cursors.top_side]
x_hotspot = 128
y_hotspot = 23
symlinks = ['n-resize']

[cursors.top_tee]
x_hotspot = 128
y_hotspot = 27

[cursors.ul_angle]
x_hotspot = 33
y_hotspot = 33

[cursors.ur_angle]
x_hotspot = 225
y_hotspot = 33

[cursors.vertical-text]

[cursors.wait]
symlinks = ['watch']

[cursors.wayland-cursor]

[cursors.X_cursor]
symlinks = ['pirate', 'x-cursor']

[cursors.xterm]
symlinks = ['ibeam', 'text']

[cursors.zoom-in]
x_hotspot = 116
y_hotspot = 116

[cursors.zoom-out]
x_hotspot = 116
y_hotspot = 116
